# -*- coding: utf-8 -*-
"""text_to_speech.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TyKOWOT1SUa_pER4RWbJILupwiXPIqC9
"""

# !pip install gTTS
from gtts import gTTS
import os
say = 'Hello Prashant Shekhar'
language = 'en'
speech = gTTS(text = say)
speech.save('/content/drive/My Drive/CSE Projects/first.mp3')

